services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_VONAGE_APPLICATION_ID=${NEXT_PUBLIC_VONAGE_APPLICATION_ID}
        - VONAGE_PRIVATE_KEY=${VONAGE_PRIVATE_KEY}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
